name: Lint, Type Check, Test, Build

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  check:
    name: Using Node ${{ matrix.node }}/${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x', '20.x']
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Check formatting
        run: yarn check:format

      - name: Check types
        run: yarn check:types

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:ci

      - name: Build
        run: yarn build
